server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: apigateway-service

  cloud:
    gateway:
      routes:
        - id: user-service-login #-- 로그인
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service-signup #-- 회원가입
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} #-- 백엔드로 요청을 보낼 때 user-service를 버리고 요청

        - id: user-service-actuator #-- actuator
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method= POST, GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment} #-- 백엔드로 요청을 보낼 때 user-service를 버리고 요청


        - id: user-service-info #-- 그 외 서비스
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
#              ----------------------------------------------------- user ------------------------------------------------
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/category-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/category-service/(?<segment>.*), /$\{segment}
#            ----------------------------------------------------- category ------------------------------------------------

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
#            ----------------------------------------------------- post ------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh